sonar.projectKey=Skill2Future
sonar.projectName=Skill2Future
sonar.projectVersion=1.0

# 1. Définition des sources (Back et Front)
sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests

# 2. Exclusions (Ne pas analyser les dépendances)
sonar.exclusions=**/vendor/**,**/node_modules/**,backend/public/**,frontend/dist/**,**/*.blade.php

# 3. Encodage
sonar.sourceEncoding=UTF-8
