# Identifiants de ton projet SonarQube
sonar.projectKey=skill2future
sonar.projectName=Skill2Future

# --- Configuration Backend (PHP/Laravel) ---
sonar.sources=backend/app,backend/routes,frontend/src
sonar.tests=backend/tests

# Lien vers le rapport Clover pour PHP
sonar.php.coverage.reportPaths=backend/build/logs/clover.xml

# --- Configuration Frontend (JS/React) ---
# Lien vers le rapport LCOV pour JS/React
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# --- Règles d'exclusions ---
# Empêche SonarQube d'analyser le code généré, les dépendances, etc.
sonar.exclusions=**/vendor/**,**/node_modules/**,**/dist/**,**/build/**,backend/storage/**,backend/bootstrap/cache/**,**/public/**,**/*.css

# Exclure les fichiers de test JS/PHP de l'analyse métier
sonar.test.inclusions=frontend/src/**/*.test.jsx,frontend/src/**/*.test.js,backend/tests/**
